"""add anon_code to users

Revision ID: 93d267453bf0
Revises: 94bd9d496d71
Create Date: 2026-02-27 23:02:20.712448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d267453bf0'
down_revision = '94bd9d496d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anon_code', sa.String(length=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_anon_code'), ['anon_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_anon_code'))
        batch_op.drop_column('anon_code')

    # ### end Alembic commands ###
